name: Auth
main: Auth\Auth
version: 6.0.2
api: [3.0.0-ALPHA4,3.0.0-ALPHA5,3.0.0-ALPHA6]
author: Pab45O

commands:

  register:
    description: "/register <password>"

  login:
    description: "/login <password>"

  unregister:
    description: "/unregister <user>"
