---
#------------------------------------------------------------------------#
register.join.message: §e§l» §r§eWelcome, Use /register <password> to logged in.
register.success.message: §a§l» §r§aYou have been logged in.
register.error.message: §c§l» §r§cUse /register <password>.

login.join.message: §e§l» §r§eWelcome, Use /login <password> to logged in.
login.success.message: §a§l» §r§aYou have been logged in.
login.success.ip.message: §a§l» §r§aYou have been logged with your Ip.
login.error.message: §c§l» §r§cWrong password.

unregister.success.message: §a§l» §r§aYou have unregister the player.
unregister.error.message: §c§l» §r§cPlayer does not exist.

kick.player.message: §cYou account has been unregister by an admin.
#------------------------------------------------------------------------#

#------------------#
mysqli.work.?: false

HOST: 127.0.0.1
USER: root
PASS: ""
#------------------#
...
